alias sail='sh $([ -f sail ] && echo sail || echo vendor/bin/sail)'
alias s='sail '
alias a='sail php artisan '
alias c='sail composer '
alias u='sail php artisan test '
alias uf='u --filter '
alias gs='git status'
alias adda='vi ~/.oh-my-zsh/custom/aliases.zsh'
alias source_profile='source ~/.zshrc'
alias his='history'

